# Generated by Django 3.1.5 on 2021-02-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='user name')),
                ('email', models.EmailField(default='', max_length=50)),
                ('no', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
