# Generated by Django 3.1.5 on 2021-02-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210218_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page',
            name='fname',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='home_page',
            name='lname',
            field=models.CharField(default='', max_length=150),
        ),
    ]
