# Generated by Django 3.1.5 on 2021-02-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210219_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page',
            name='cpassword',
            field=models.CharField(default='', max_length=100),
        ),
    ]
