# Generated by Django 3.1.4 on 2021-02-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_home_page_cpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page',
            name='lname',
            field=models.CharField(default='', max_length=160),
        ),
    ]
