# Generated by Django 3.1.7 on 2021-03-24 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210226_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page',
            name='lname',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.CreateModel(
            name='Userbase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='', max_length=150)),
                ('add_images', models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='ProdsImages/')),
                ('add_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.home_page')),
            ],
        ),
    ]
